version: '3.8'

services:
    nginx:
        image: nginx:latest
        container_name: nginx
        restart: unless-stopped
        tty: true
        volumes:
            - ./nginx/conf.d/:/etc/nginx/conf.d/
            - ../:/var/www:ro
        networks:
            - app-network
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - php

    php:
        build:
            context: .
            dockerfile: php/Dockerfile
        container_name: php
        restart: unless-stopped
        tty: true
        ports:
            - "9000:9000"
        volumes:
            - ../:/var/www
        depends_on:
            - mysql
        networks:
            - app-network

    ofelia:
        image: mcuadros/ofelia:latest
        volumes:
            - //var/run/docker.sock:/var/run/docker.sock:ro
            - ./ofelia/config.ini:/etc/ofelia/config.ini
        restart: always
        networks:
            - app-network

    horizon:
        build:
            context: .
            dockerfile: php/Dockerfile
        restart: always
        container_name: horizon
        command: [ "php", "/var/www/artisan", "horizon" ]
        ports:
            - "9001:9000"
        tty: true
        volumes:
            - ../:/var/www
        depends_on:
            - mysql
        networks:
            - app-network

    mysql:
        image: mysql:8.0
        restart: always
        container_name: mysql
        volumes:
            - mysql-data:/var/lib/mysql
        environment:
            MYSQL_DATABASE: univex
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        command: [
            "mysqld",
            "--character-set-server=utf8",
            "--collation-server=utf8_unicode_ci",
            "--innodb-ft-min-token-size=1"
        ]
        networks:
            - app-network

    minio:
        image: minio/minio:latest
        container_name: minio
        restart: always
        ports:
            - "3377:9000"
            - "3388:9001"
        command: server /data --console-address ":9001"
        environment:
            MINIO_ROOT_USER: minio
            MINIO_ROOT_PASSWORD: rootroot
        volumes:
            - minio-univex:/data
        networks:
            - app-network

    phpmyadmin:
        image: phpmyadmin:latest
        container_name: pma
        ports:
            - "8877:80"
        environment:
            PMA_HOST: "89.253.237.41"
            PMA_PORT: "3310"
            UPLOAD_MAX_FILESIZE: 512M
            POST_MAX_SIZE: 512M
            MAX_EXECUTION_TIME: 3000
        networks:
            - app-network

    phpmyadmin1:
        image: phpmyadmin:latest
        container_name: pma1
        ports:
            - "8876:80"
        environment:
            PMA_HOST: mysql
            UPLOAD_MAX_FILESIZE: 512M
            POST_MAX_SIZE: 512M
            MAX_EXECUTION_TIME: 3000
            PMA_ARBITRARY: 0
        depends_on:
            - mysql
        networks:
            - app-network

    redis:
        container_name: redis
        image: redis:latest
        restart: always
        command: redis-server
            --requirepass ${REDIS_PASSWORD}
        environment:
            - REDIS_PASSWORD=${REDIS_PASSWORD}
        networks:
            - app-network

    meilisearch:
        image: getmeili/meilisearch
        container_name: meilisearch
        restart: unless-stopped
        environment:
            - MEILI_ENV=development
            - MEILI_NO_ANALYTICS=true
        volumes:
            - meilisearch_data:/meili_data
        networks:
            - app-network

volumes:
    mysql-data:
    minio-univex:
    meilisearch_data:
#    vault-data:

networks:
    app-network:
        driver: bridge
